# Generated by Django 4.2 on 2023-04-13 17:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('imovel', '0001_initial'),
        ('locador', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Locatario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_entrada_imovel', models.DateField(blank=True, null=True, verbose_name='Data de entrada no imovel')),
                ('data_nascimento', models.DateField()),
                ('imovel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='imovel.imovel')),
                ('locador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='locador.locador')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
