# Generated by Django 4.2 on 2023-04-17 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locador', '0002_remove_locador_mes_pago_locador_telefone_and_more'),
        ('locatario', '0002_locatario_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locatario',
            name='locador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locador.locador'),
        ),
    ]
