# Generated by Django 4.2 on 2023-04-20 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imovel', '0002_alter_imovel_nome'),
        ('locatario', '0003_alter_locatario_locador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locatario',
            name='imovel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='imovel.imovel'),
        ),
    ]
