# Generated by Django 4.1.7 on 2023-02-21 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0007_remove_perfil_bairro_remove_perfil_cep_and_more'),
        ('imobiliaria', '0002_imovel_mensalidade_alter_imovel_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='imovel',
            name='vencimento',
            field=models.IntegerField(default=1, verbose_name='Vencimento da mensalidade'),
        ),
        migrations.CreateModel(
            name='HistoricoPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataReferencia', models.DateField(auto_now=True, verbose_name='Data de referencia do pagamento')),
                ('imovel', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='imobiliaria.imovel')),
                ('perfil', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='usuario.perfil')),
            ],
        ),
    ]
