# Generated by Django 4.1.7 on 2023-02-21 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imobiliaria', '0003_imovel_vencimento_historicopagamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicopagamento',
            name='imovel',
        ),
        migrations.AddField(
            model_name='historicopagamento',
            name='pago',
            field=models.BooleanField(default=True, verbose_name='Pagamento efetuado?'),
        ),
    ]
