# Generated by Django 4.1.7 on 2023-02-22 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imobiliaria', '0005_delete_historicopagamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imovel',
            name='bairro',
        ),
        migrations.RemoveField(
            model_name='imovel',
            name='cep',
        ),
        migrations.RemoveField(
            model_name='imovel',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='imovel',
            name='endereco',
        ),
        migrations.RemoveField(
            model_name='imovel',
            name='mensalidade',
        ),
        migrations.RemoveField(
            model_name='imovel',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='imovel',
            name='numeroEndereco',
        ),
        migrations.RemoveField(
            model_name='imovel',
            name='uf',
        ),
        migrations.RemoveField(
            model_name='imovel',
            name='vencimento',
        ),
    ]
