# Generated by Django 4.1.7 on 2023-02-22 18:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('imobiliaria', '0006_remove_imovel_bairro_remove_imovel_cep_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imovel',
            name='bairro',
            field=models.CharField(blank=True, max_length=100, verbose_name='Bairro'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='cep',
            field=models.CharField(blank=True, max_length=9, verbose_name='CEP'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='cidade',
            field=models.CharField(blank=True, max_length=100, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='endereco',
            field=models.CharField(blank=True, max_length=100, verbose_name='Endereço'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='mensalidade',
            field=models.FloatField(blank=True, default=0.0, verbose_name='Mensalidade'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='nome',
            field=models.CharField(blank=True, max_length=50, verbose_name='Nome do imóvel / vila / condominio'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='numeroEndereco',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nº'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='uf',
            field=models.CharField(blank=True, max_length=2, verbose_name='UF'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='vencimento',
            field=models.IntegerField(default=1, verbose_name='Vencimento da mensalidade'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
