# Generated by Django 4.1.7 on 2023-02-24 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imobiliaria', '0009_alter_imovel_mensalidade_alter_imovel_vencimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imovel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='vencimento',
            field=models.IntegerField(default=10, verbose_name='Dia do vencimento da mensalidade'),
        ),
    ]
