# Generated by Django 4.1.7 on 2023-02-24 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imobiliaria', '0010_alter_imovel_id_alter_imovel_vencimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='imovel',
            name='disponibilidade',
            field=models.BooleanField(default=True, verbose_name='Disponibilidade'),
        ),
    ]
