# Generated by Django 4.1.7 on 2023-02-27 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imobiliaria', '0011_imovel_disponibilidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imovel',
            name='mensalidade',
            field=models.FloatField(blank=True, max_length=10, verbose_name='Mensalidade R$'),
        ),
    ]
