# Generated by Django 4.1.7 on 2023-02-27 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imobiliaria', '0012_alter_imovel_mensalidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='imovel',
            name='mensalidade2',
            field=models.CharField(blank=True, max_length=10, verbose_name='Mensalidade 2'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='mensalidade',
            field=models.CharField(blank=True, max_length=10, verbose_name='Mensalidade'),
        ),
    ]
