# Generated by Django 4.1.7 on 2023-02-27 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imobiliaria', '0013_imovel_mensalidade2_alter_imovel_mensalidade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imovel',
            name='mensalidade2',
        ),
    ]
