# Generated by Django 4.1.7 on 2023-03-06 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imobiliaria', '0015_alter_imovel_mensalidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imovel',
            name='cep',
            field=models.CharField(max_length=9, verbose_name='CEP'),
        ),
    ]
