# Generated by Django 4.1.7 on 2023-03-15 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imobiliaria', '0017_alter_imovel_cep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imovel',
            name='mensalidade',
            field=models.IntegerField(blank=True, max_length=10, verbose_name='Mensalidade R$'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='vencimento',
            field=models.IntegerField(default=5, verbose_name='Dia do vencimento da mensalidade'),
        ),
    ]
