# Generated by Django 4.1.7 on 2023-03-20 18:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imobiliaria', '0018_alter_imovel_mensalidade_alter_imovel_vencimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imovel',
            name='mensalidade',
            field=models.IntegerField(blank=True, validators=[django.core.validators.MaxValueValidator(999999), django.core.validators.MinValueValidator(0)], verbose_name='Mensalidade R$'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='vencimento',
            field=models.IntegerField(default=5, validators=[django.core.validators.MaxValueValidator(29), django.core.validators.MinValueValidator(1)], verbose_name='Dia do vencimento da mensalidade'),
        ),
    ]
