# Generated by Django 4.1.7 on 2023-03-20 18:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imobiliaria', '0019_alter_imovel_mensalidade_alter_imovel_vencimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imovel',
            name='mensalidade',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(999999), django.core.validators.MinValueValidator(0)], verbose_name='Mensalidade R$'),
        ),
    ]
