# Generated by Django 4.2 on 2023-04-14 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locador', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locador',
            name='mes_pago',
        ),
        migrations.AddField(
            model_name='locador',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='locador',
            name='ultimo_pagamento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
