# Generated by Django 4.1.7 on 2023-02-20 16:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='bairro',
            field=models.CharField(blank=True, max_length=100, verbose_name='Bairro'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='cep',
            field=models.CharField(blank=True, max_length=9, verbose_name='CEP'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='cidade',
            field=models.CharField(blank=True, max_length=100, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Data da Inclusão'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perfil',
            name='endereco',
            field=models.CharField(blank=True, max_length=100, verbose_name='Endereço'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ativo?'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='É da equipe de administração?'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='numeroEndereco',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nº'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='uf',
            field=models.CharField(blank=True, max_length=2, verbose_name='UF'),
        ),
    ]
