# Generated by Django 4.1.7 on 2023-02-20 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_perfil_bairro_perfil_cep_perfil_cidade_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='date_joined',
        ),
    ]
