# Generated by Django 4.1.7 on 2023-02-20 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_alter_perfil_options_alter_perfil_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='nome_completo',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
