# Generated by Django 4.1.7 on 2023-02-21 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0008_historicopagamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicopagamento',
            name='imovel',
        ),
    ]
