# Generated by Django 4.1.7 on 2023-02-22 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imobiliaria', '0007_imovel_bairro_imovel_cep_imovel_cidade_and_more'),
        ('usuario', '0010_alter_historicopagamento_id_alter_perfil_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='imovel',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.PROTECT, to='imobiliaria.imovel'),
        ),
    ]
