# Generated by Django 4.1.7 on 2023-02-23 13:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('imobiliaria', '0009_alter_imovel_mensalidade_alter_imovel_vencimento'),
        ('usuario', '0012_alter_perfil_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='imovel',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='imobiliaria.imovel'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='usuario',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
