# Generated by Django 4.1.7 on 2023-02-23 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imobiliaria', '0009_alter_imovel_mensalidade_alter_imovel_vencimento'),
        ('usuario', '0013_alter_perfil_imovel_alter_perfil_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='imovel',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='imobiliaria.imovel'),
        ),
    ]
