# Generated by Django 4.1.7 on 2023-02-26 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0016_alter_historicopagamento_id_alter_perfil_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='data_entrada_imovel',
            field=models.DateField(auto_now=True),
        ),
    ]
