# Generated by Django 4.1.7 on 2023-02-26 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0018_alter_perfil_data_entrada_imovel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='data_entrada_imovel',
            field=models.DateField(auto_now_add=True, verbose_name='Data de entrada no imovel'),
        ),
    ]
