# Generated by Django 4.1.7 on 2023-02-28 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0021_alter_perfil_data_nascimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='nome_completo',
            field=models.CharField(max_length=50, null=True, verbose_name='Nome completo'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='telefone',
            field=models.CharField(max_length=16, null=True, verbose_name='Telefone para contato'),
        ),
        migrations.DeleteModel(
            name='HistoricoPagamento',
        ),
    ]
