# Generated by Django 4.1.7 on 2023-03-06 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0022_alter_perfil_nome_completo_alter_perfil_telefone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='data_entrada_imovel',
            field=models.DateField(verbose_name='Data de entrada no imovel'),
        ),
    ]
