# Generated by Django 4.1.7 on 2023-03-06 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imobiliaria', '0015_alter_imovel_mensalidade'),
        ('usuario', '0023_alter_perfil_data_entrada_imovel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='imovel',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='imobiliaria.imovel'),
        ),
    ]
