# Generated by Django 4.1.7 on 2023-03-06 14:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imobiliaria', '0017_alter_imovel_cep'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuario', '0025_alter_perfil_data_entrada_imovel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='data_entrada_imovel',
            field=models.DateField(auto_now_add=True, verbose_name='Data de entrada no imovel'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='data_nascimento',
            field=models.DateField(max_length=10, null=True, verbose_name='Data de nascimento'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='imovel',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='imobiliaria.imovel'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='telefone',
            field=models.CharField(max_length=16, null=True, verbose_name='Telefone para contato'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='usuario',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
