# Generated by Django 4.1.7 on 2023-03-23 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0029_alter_perfil_cpf_alter_perfil_data_nascimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='data_nascimento',
            field=models.DateField(blank=True, max_length=10, null=True, verbose_name='Data de nascimento'),
        ),
    ]
