# Generated by Django 4.1.7 on 2023-03-26 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0032_alter_perfil_data_entrada_imovel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='data_entrada_imovel',
            field=models.DateField(blank=True, null=True, verbose_name='Data de entrada no imovel'),
        ),
    ]
