# Generated by Django 4.1.7 on 2023-02-28 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamento',
            name='status',
            field=models.CharField(choices=[('C', 'Concluido'), ('N', 'Não efetuado')], max_length=20, verbose_name='Status do pagamento'),
        ),
    ]
