# Generated by Django 4.2 on 2023-04-21 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamento', '0002_pagamento_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamento',
            name='data',
            field=models.DateField(),
        ),
    ]
