# Generated by Django 4.1.7 on 2023-02-28 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0022_alter_perfil_nome_completo_alter_perfil_telefone_and_more'),
        ('pagamento', '0004_pagamento_valor_pago_alter_pagamento_data_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagamento',
            name='perfil',
        ),
        migrations.AddField(
            model_name='pagamento',
            name='perfil',
            field=models.ManyToManyField(null=True, to='usuario.perfil', verbose_name='Usuario pagador'),
        ),
    ]
