# Generated by Django 4.1.7 on 2023-02-28 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0022_alter_perfil_nome_completo_alter_perfil_telefone_and_more'),
        ('pagamento', '0005_remove_pagamento_perfil_pagamento_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamento',
            name='perfil',
            field=models.ManyToManyField(to='usuario.perfil', verbose_name='Usuario pagador'),
        ),
    ]
