# Generated by Django 4.1.7 on 2023-02-28 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0022_alter_perfil_nome_completo_alter_perfil_telefone_and_more'),
        ('pagamento', '0006_alter_pagamento_perfil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagamento',
            name='perfil',
        ),
        migrations.AddField(
            model_name='pagamento',
            name='perfil',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuario.perfil', verbose_name='Usuario pagador'),
        ),
    ]
