# Generated by Django 4.1.7 on 2023-02-28 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamento', '0007_remove_pagamento_perfil_pagamento_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamento',
            name='data',
            field=models.DateField(auto_now_add=True, verbose_name='Data do pagamento'),
        ),
    ]
