# Generated by Django 4.1.7 on 2023-02-28 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamento', '0008_alter_pagamento_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamento',
            name='data',
            field=models.DateField(blank=True, null=True, verbose_name='Data do pagamento'),
        ),
    ]
