# Generated by Django 4.1.7 on 2023-03-02 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamento', '0010_alter_pagamento_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamento',
            name='status',
            field=models.CharField(choices=[(0, 'Pago'), (1, 'Em Análise')], default='A', max_length=20, verbose_name='Status do pagamento'),
        ),
    ]
