# Generated by Django 4.1.7 on 2023-03-15 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0027_alter_perfil_data_nascimento_alter_perfil_imovel'),
        ('pagamento', '0016_alter_pagamento_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamento',
            name='perfil',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuario.perfil', verbose_name='Usuario pagador'),
        ),
    ]
