# Generated by Django 4.1.7 on 2023-03-15 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamento', '0017_alter_pagamento_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamento',
            name='valor_pago',
            field=models.IntegerField(max_length=10, null=True, verbose_name='Valor pago'),
        ),
    ]
