# Generated by Django 4.1.7 on 2023-03-15 18:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamento', '0018_alter_pagamento_valor_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamento',
            name='valor_pago',
            field=models.IntegerField(max_length=10, null=True, validators=[django.core.validators.MaxValueValidator], verbose_name='Valor pago'),
        ),
    ]
