# Generated by Django 4.1.7 on 2023-03-20 18:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamento', '0019_alter_pagamento_valor_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamento',
            name='valor_pago',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(999999), django.core.validators.MinValueValidator(0)], verbose_name='Valor pago'),
        ),
    ]
